### PR TITLE
fix: Tensor conversion for expected data in _MainModel

### LINKED ISSUE #1043: Missing tensorlib conversion for Model.main_model.expected_data
# Description

This is the same issue as #1027, but for `Model.main_model.expected_data` instead. I missed it earlier due to the workaround I had been using for #1027. That function is particularly interesting for the `return_by_sample` behavior introduced by #731.

```
import pyhf

model = pyhf.simplemodels.hepdata_like(
    signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
)

model.main_model.expected_data(model.config.suggested_init())
```

results in

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model.main_model.expected_data(model.config.suggested_init())
  File "[...]pyhf/src/pyhf/pdf.py", line 517, in expected_data
    deltas, factors = self._modifications(pars)
  File "[...]pyhf/src/pyhf/pdf.py", line 483, in _modifications
    [self.modifiers_appliers[k].apply(pars) for k in self._factor_mods],
  File "[...]pyhf/src/pyhf/pdf.py", line 483, in <listcomp>
    [self.modifiers_appliers[k].apply(pars) for k in self._factor_mods],
  File "[...]pyhf/src/pyhf/modifiers/shapesys.py", line 169, in apply
    shapefactors = tensorlib.gather(flat_pars, self.access_field)
  File "[...]pyhf/src/pyhf/tensor/numpy_backend.py", line 136, in gather
    return tensor[indices]
TypeError: only integer scalar arrays can be converted to a scalar index
```

# Expected Behavior

no crash, but successful return of expected data

# Actual Behavior

crash with `TypeError: only integer scalar arrays can be converted to a scalar index`

# Steps to Reproduce

`pyhf` master @ 236fbaa, see above

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [ ] Searched through existing Issues to confirm this is not a duplicate issue
- [ ] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

### PR DESCRIPTION
**Pull request by alexander-held**
# Description

This resolves #1043.

By adding a tensor conversion for the parameters handed to `_MainModel.expected_data`, the behavior matches the other related functions:

- `pyhf.pdf.Model.expected_actualdata`
- `pyhf.pdf.Model.expected_auxdata`
- `pyhf.pdf.Model.expected_data`

This enables running the following:

```python
import pyhf

model = pyhf.simplemodels.hepdata_like(
    signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
)

model.main_model.expected_data(model.config.suggested_init())
```

Also adding a test for the behavior that would fail on the current master branch.

Related PR: #1027, which fixed the behavior for `expected_actualdata` and `expected_auxdata`.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Ensure the parameters of pdf._MainModel.expected_data are tensors
   - Amends PR #1038 
* Add test for pdf._MainModel.expected_data acceptance of list instead of tensor
```

### CODE REVIEW

**Comment by lukasheinrich** [comment]
nice to see this in. just one comment for reference: we at some point removed all internal "astensor" calls since we found out they're not free performance wise, in this case though it's probably not too bad.

**Comment by matthewfeickert** [comment]
> nice to see this in. just one comment for reference: we at some point removed all internal "astensor" calls since we found out they're not free performance wise, in this case though it's probably not too bad.

Yeah, I figured that as this is all happening in the model section and not in the tensor computations of evaluating anything that small performance hits would be okay.

**Comment by kratsg** [comment]
> nice to see this in. just one comment for reference: we at some point removed all internal "astensor" calls since we found out they're not free performance wise, in this case though it's probably not too bad.

One thought I had towards this end is that we split everything up as public API with astensor calls and internal API without:

```python
def expected_data(.....):
  return self._expected_data(tensorlib.astensor(....))
```

This should help us keep user-friendly interfaces while maintaining performance.

**Comment by matthewfeickert** [comment]
> One thought I had towards this end is that we split everything up as public API with astensor calls and internal API without:
> 
> ```python
> def expected_data(.....):
>   return self._expected_data(tensorlib.astensor(....))
> ```
> 
> This should help us keep user-friendly interfaces while maintaining performance.

@kratsg Can you make an issue for this with a deliverable?

**Pull request merged**
