### PR TITLE
fix: Correct iminuit optimizer verbose setting typo

### PR DESCRIPTION
**Pull request by ntadej**
# Description

It seems there's a typo in the minuit optimiser and it can never be set verbose. This MR should fix it.

Note that I have problems setting up all the test dependencies (notably tensorflow 1 seems to be hard to install these days now that v2 is default). Let's see what GitHub Actions have to say.

# Checklist Before Requesting Reviewer

- [ ] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

### CODE REVIEW

**Comment by ntadej** [comment]
CI is also unhappy about TF version compatibility. I'll try to fix it tomorrow.

**Comment by matthewfeickert** [comment]
Hi @ntadej Thanks very much for the PR! :rocket: What you're currently experiencing with the TensorFlow failure is hitting everything due to the conflict with TensorFlow Probability requirments. We'll be merging in PR #541 very soon, which fixes this, so after that is done if you just rebase you should be good to go!

**Comment by matthewfeickert** [comment]
@ntadej Can you please rebase the PR against `master` to try and bump Codecov (which seems stuck) and then fill out the rest of the PR body?

**Comment by kratsg** [comment]
NB: #728 will fix the canary failing.

**Pull request merged**
