### PR TITLE
docs: Add developer release checklist Issue template

### LINKED ISSUE #1319: Create a developer release checklist system
To properly test the new codemeta requirements you need to install the library. This should be done in a new virtual environment to make sure that a clean install is getting picked up. This should get added to a developer release checklist, as there are now enough things needed to cleanly cut a release that it is to much to remember all at once.

_Originally posted by @matthewfeickert in https://github.com/scikit-hep/pyhf/issues/1318#issuecomment-779645881_

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #1319

Add a developer release checklist Issue Template to make sure that steps don't get missed during the release and to formalize the release so that any member of the developer team can do it.

Restrict the issue template to project maintainers only. c.f. https://github.com/pypa/pip/blob/e6414d6db6db37951988f6f2b11ec530ed0b191d/.github/ISSUE_TEMPLATE/~good-first-issue.md for an example.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add a developer release checklist GitHub Issue template
   - Restrict the Issue template to be usable by project maintainers only
* Add a section to the development docs mentioning the Issue template
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Relevant page for review: https://pyhf--1493.org.readthedocs.build/en/1493/development.html

**Review by kratsg — CHANGES_REQUESTED** [review]
Shouldn't we add an ISSUE_TEMPLATE for release checklist instead? I'm not sure it needs to be added to the docs explicitly but...

**Comment by matthewfeickert** [comment]
> Shouldn't we add an ISSUE_TEMPLATE for release checklist instead? I'm not sure it needs to be added to the docs explicitly but...

Yeah, that's a much better idea. I originally had this as part of a PR comment, but then changed to an Issue. I'll fix this up. :+1:

**Comment by matthewfeickert** [comment]
Probably easiest way to review online is to read here: https://github.com/scikit-hep/pyhf/blob/docs/add-developer-release-checklist/.github/ISSUE_TEMPLATE/~release-checklist.md

**Pull request merged**
