### PR TITLE
chore: Use exc_info in log.error, re-raise last exceptions

### LINKED ISSUE #1195: chore: Use exc_info in log.error to show error as well as the message
quick tip - `repr(excep)` will show the error as well as the message
```
In [1]: try:
   ...:     1/0
   ...: except Exception as e:
   ...:     print(repr(e))
   ...: 
ZeroDivisionError('division by zero')

In [2]: try:
   ...:     1/0
   ...: except Exception as e:
   ...:     print(str(e))
   ...: 
division by zero
```

_Originally posted by @MarcoGorelli in https://github.com/scikit-hep/pyhf/pull/1194#discussion_r529733090_

This happens in two places in the codebase:

```
$ git grep "str(excep)"
src/pyhf/contrib/cli.py:            str(excep)
src/pyhf/contrib/utils.py:        str(excep)
```

and so would be a good first issue for someone who wanted to make a small PR.

### PR DESCRIPTION
**Pull request by kratsg**
# Pull Request Description

This will resolve #1195.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR
```
* Use exc_info in log.error to show error + message
* Use raise without arguments to re-raise last raised exception
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@kratsg This PR idea is fine, but why does this need to be a patch release and not just part of the upcoming `v0.6.0` minor release?

**Comment by matthewfeickert** [comment]
So the motivation for the patch release if I understand this correctly is that while we properly pinned things in `v0.5.3` thanks to @jpivarski's advice as to not break `uproot` in the future and that works 

```
# pip install --quiet pyhf[xmlio]
# pip list
Package        Version
-------------- -------
attrs          20.3.0
awkward        0.14.0
cachetools     4.1.1
click          7.1.2
jsonpatch      1.28
jsonpointer    2.0
jsonschema     3.2.0
numpy          1.19.4
pip            20.3.1
pyhf           0.5.3
pyrsistent     0.17.3
PyYAML         5.3.1
scipy          1.5.4
setuptools     50.3.2
six            1.15.0
tqdm           4.54.1
uproot         3.13.1
uproot-methods 0.8.0
wheel          0.36.0
```

However, it seems that @alexander-held has found issues where this is breaking the dev cycle of `cabinetry` that uses `uproot4` as

```
# pip install pyhf[xmlio]
# pip list | grep uproot
uproot         3.13.1
uproot-methods 0.8.0
# pip install uproot4
# pip list | grep uproot
uproot         4.0.0
uproot-methods 0.8.0
uproot4        4.0.0
```

So this means that anyone who wants to try to use `pyhf` and `uproot` `v4.x` in the same environment is in for some trouble, but a patch would fix this:

```
# python -m pip install --quiet --extra-index-url https://test.pypi.org/simple/ --pre pyhf[xmlio]
# pip list
Package         Version
--------------- -----------
attrs           20.3.0
awkward0        0.15.1
cachetools      4.1.1
click           8.0.0a1
jsonpatch       1.28
jsonpointer     2.0
jsonschema      3.2.0
numpy           1.20.0rc1
pip             20.3.1
pyhf            0.5.4.dev27
pyrsistent      0.17.3
PyYAML          5.3.1
scipy           1.5.4
setuptools      50.3.2
six             1.15.0
tqdm            4.54.1
uproot3         3.14.1
uproot3-methods 0.10.0
wheel           0.36.0
# pip list | grep uproot
uproot          4.0.0
uproot3         3.14.1
uproot3-methods 0.10.0
```

While I was originally against this idea I think that this might be necessary to ensure that `pyhf` `v3.x` release work in the future.

**Comment by alexander-held** [comment]
There may be one other solution I did not think of before - pinning `uproot4==0.1.2` should keep the `uproot` namespace clean. That however does not help users who want the latest `uproot` at some point in the future, whether they install it as `uproot` or `uproot4`.

**Comment by matthewfeickert** [comment]
> That however does not help users who want the latest `uproot` at some point in the future, whether they install it as `uproot` or `uproot4`.

Yeah, what changed my mind on if this should be a patch release vs. going into `v0.6.0` is that a user in the future trying to use `pyhf` `v0.5.x` would have `uproot` broken for them unless they magically knew to pin to this version.

**Review by matthewfeickert — APPROVED** [review]
Thanks for the PR @kratsg. I'll obviously approve it, and if we're still in agreement on the idea of a patch release then we can keep the label on there too. :+1:

**Comment by jpivarski** [comment]
Be sure to only pin (a subset of) `uproot3`, `uproot>=4.0.0`, `awkward0`, `awkward>=1.0.0`. In particular, don't pin `uproot-methods`.

I had to add an `uproot3-methods` to avoid incompatibilities with old `uproot-methods` packages that did not explicitly require `awkward<1.0.0`. The package named `uproot-methods` should be dropped entirely.

**Comment by matthewfeickert** [comment]
> Be sure to only pin (a subset of) `uproot3`, `uproot>=4.0.0`, `awkward0`, `awkward>=1.0.0`. In particular, don't pin `uproot-methods`.

Yup. We just use compatible releases for `uproot3`

https://github.com/scikit-hep/pyhf/blob/0370dbd5d728b2be90bab95c020ca85b384657b8/setup.py#L11

**Comment by jpivarski** [comment]
After talking with @alexander-held and @matthewfeickert in the Analysis Systems meeting, I recommended updating pyhf to the new Uproot/Awkward names (including `uproot3` and `awkward0` as "new names"), rather than back-porting Cabinetry. It's true that if users have old names, they'll have conflicts, but users need to update to new names, too.

The reason I introduced new names for the old interfaces is to allow scripts and analyses to continue with minimal disruption while also "living at head" with the latest versions. Technically, `uproot3` and `awkward0` are the "latest versions" of these old projects.

In particular, I think it's a better idea to release a patch version of pyhf that only changes the Uproot/Awkward dependencies without stealthily adding 0.6.0 features. Even though there isn't a branch for 0.5.x, it's not hard to make one: (1) git checkout the latest 0.5.x tag (0.5.3), (2) create a branch for this detached HEAD state, (3) spot-change the dependencies, and (4) push to GitHub, where you can make a tag to deploy from this 0.5.x branch.

**Comment by matthewfeickert** [comment]
For the time being I'm going to remove the patch-release label from this PR, until we finalize the discussion #1211.

**Pull request merged**
