### PR TITLE
test: Add public API canary tests to CI and nightly tests for current PyPI release

### LINKED ISSUE #605: Add smoketests to make sure that the public API is stable
# Description

As a (somewhat redundant) set of reliability tests, tests that directly test common usages of the public API could be added. This could verify that we don't merge anything that changes the public API without also having to cut a new release.

### LINKED ISSUE #609: Add nightly cron jobs to test PyPI installs
# Description

Related to Issue #605, the PyPI release should be tested nightly. Given that after PR #592 was merged we didn't cut a release this means that `v0.1.2` on PyPI is currently broken for the TensorFlow backend.

```
$ pip install pyhf[xmlio,tensorflow]
$ python
>>> import tensorflow as tf
>>> import pyhf
>>> sess = tf.Session()
2019-10-10 16:31:14.108012: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-10 16:31:14.112827: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2194695000 Hz
2019-10-10 16:31:14.113210: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4b91460 executing computations on platform Host. Devices:
2019-10-10 16:31:14.113226: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
>>> 
>>> pyhf.set_backend(pyhf.tensor.tensorflow_backend(sess))
Traceback (most recent call last):
  File "/home/mcf/venvs/pypi-pyhf/lib/python3.6/site-packages/pyhf/tensor/__init__.py", line 28, in __getattr__
    from .tensorflow_backend import tensorflow_backend
  File "/home/mcf/venvs/pypi-pyhf/lib/python3.6/site-packages/pyhf/tensor/tensorflow_backend.py", line 3, in <module>
    import tensorflow_probability as tfp
  File "/home/mcf/venvs/pypi-pyhf/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/mcf/venvs/pypi-pyhf/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.15; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcf/venvs/pypi-pyhf/lib/python3.6/site-packages/pyhf/tensor/__init__.py", line 37, in __getattr__
    e,
pyhf.exceptions.ImportBackendError: ('There was a problem importing TensorFlow. The tensorflow backend cannot be used.', ImportError('This version of TensorFlow Probability requires TensorFlow version >= 1.15; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.',))
```

To avoid having releases break on users we should add tests that run nightly as cron jobs that install from PyPI and then run through a series of API tests.

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

- Resolves #609 
- Resolves #605 

Add canary tests and GitHub Actions workflow to check if the current release of pyhf on PyPI is functional and able to work with the current API.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add GitHub Actions workflow to nightly check if the current release of pyhf on PyPI is valid for the public API
* Add canary tests of the public API
   - Runs on both GitHub in CI and in against the releases from PyPI
* Use tf.compat.v1.Session to avoid warning
```

### CODE REVIEW

**Comment by kratsg** [comment]
I'm actually pretty iffy about having separate tests just for the public API. These should just be covered already by the existing tests, no? Or the point is to figure out when the API changes?

**Comment by lukasheinrich** [comment]
yeah that's the point. It will not be comprehensive.. but it would be a
point of APIs where we can say "this is definitely what we won't break
without bumping a release".

**Comment by matthewfeickert** [comment]
> These should just be covered already by the existing tests, no? Or the point is to figure out when the API changes?

Exactly. As the Codecov coverage report shows these tests don't increase the coverage at all (it would be bad if they did!). The real reason these tests are being added is for the PyPI release nightly public API tests, as these tests can fail without affecting anything (and in fact the first time these run as a nightly they _will_ fail (as expected) as we [don't have `pyhf.probability` in the `v0.1.2` release](https://github.com/diana-hep/pyhf/runs/287654196#step:5:23)). But in the future, if they fail then that's a good sign to us that we should consider a new release soon.

It just seemed like there was no harm in having the CI run them as well.

**Comment by kratsg** [comment]
Maybe add a comment somewhere of a "public API canary" rather than "testing the public API" since that's not necessarily what we're doing. This is probably a bit pedantic but ok...

**Comment by matthewfeickert** [comment]
@lukasheinrich If we can get your review on this then it is ready to go in. A note though, this will break when it runs its first nightly test but that's just doing its job by telling us we need to cut a new release. :)

**Comment by kratsg** [comment]
maybe add a test to ensure the batching support?

**Pull request merged**
