### PR TITLE
ci: Restrict deployments of environments to PR merges

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Split the docs workflow into a build and deploy jobs, where the deploy job requires the build job to succeed. This avoids unnecessary deployments by only having the github-pages environment exist in the deploy job.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Split the docs workflow into a build and deploy jobs, where the deploy
  job requires the build job to succeed. This avoids unnecessary deployments
  by only having the github-pages environment exist in the deploy job.
* Constrain the deployment of environments to PR merges by requiring push
  events on master to trigger the deploy job.

Co-authored-by: Giordon Stark <kratsg@gmail.com>
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Hm. @kratsg this isn't having the intended effect with [deployment history](https://github.com/scikit-hep/pyhf/deployments/activity_log?environment=github-pages).

Screenshot from 2022-08-26 10-49-00

**Review by kratsg — APPROVED** [review]

**Comment by kratsg** [comment]
Is this still a draft?

**Comment by matthewfeickert** [comment]
> Is this still a draft?

Yes, as this isn't having the intended effect. c.f. https://github.com/scikit-hep/pyhf/pull/1960#issuecomment-1228661994

**Comment by kratsg** [comment]
> Yes, as this isn't having the intended effect. c.f. [#1960 (comment)](https://github.com/scikit-hep/pyhf/pull/1960#issuecomment-1228661994)

It should be fixed now. I moved the environment + permissions to a deploy job and that job only runs on master. Pages artifacts still uploads, but now the environment isn't being created or deployed to.

**Pull request merged**
