### PR TITLE
fix: Avoid deprecation warnings due to invalid escape sequences

### PR DESCRIPTION
**Pull request by tirkarthi**
# Description

Fix deprecation warnings due to invalid escape sequences by using raw strings

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Fix deprecation warnings due to invalid escape sequences by using raw strings
```

### CODE REVIEW

**Comment by tirkarthi** [comment]
My PR is failing the commit message check I am not sure of the change that needs to be done

**Comment by matthewfeickert** [comment]
Thanks for the PR. If it is addressing Issue #1021, it would be good if this could get all of them in a single PR. If that's not in scope of your time the core devs can pick the remaining issues up later and fix them here, so I've put this as a draft for the time being.

> My PR is failing the commit message check I am not sure of the change that needs to be done

As the CI is mentioning, it just isn't following the [Semantic PR](https://github.com/zeke/semantic-pull-requests) style, but I've effectively fixed it.

**Comment by tirkarthi** [comment]
The PR is complete. They are compile time warnings and can be found with the command `find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}` . Before PR calculators.py will emit the warning. After PR no warnings are raised. Thanks for taking care of commit message.

**Comment by lukasheinrich** [comment]
maybe we should add sth like `find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}` to the CI @matthewfeickert ?

**Comment by matthewfeickert** [comment]
> maybe we should add sth like `find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}` to the CI?

Agreed, that should end up in this PR as well so we catch things like this in the future. I probably won't have time to add this in until Friday night given the computing bootcamp this week though.

**Comment by tirkarthi** [comment]
This is detected by flake8 rule number W605 as well which will be more helpful compared to the find command.

**Comment by lukasheinrich** [comment]
thanks @tirkarthi  we lint our code with `pyflakes` https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/lint.yml#L25. Is there a similar rule there?

**Comment by tirkarthi** [comment]
This seems to be an open issue in pyflakes : https://github.com/PyCQA/pyflakes/issues/437 . A sample implementation was closed https://github.com/PyCQA/pyflakes/issues/312 .

**Review by matthewfeickert — APPROVED** [review]
Thanks very much for this contribution @tirkarthi! I'm just going to take care of catching things like this again when we deal with moving to `flake8` in Issue #863. :+1:

**Pull request merged**
