### PR TITLE
chore: Use module level __dir__ to restrict public API views

### LINKED ISSUE #1402: Use module level __dir__ for cleaner REPL import completion
# Description

Stealing this from @henryiii who found it from Brett Cannon's blog [An approach to lazy importing in Python 3.7](https://snarky.ca/lazy-importing-in-python-3-7/) and implemented it for `hist` in https://github.com/scikit-hep/hist/pull/179:

> I’ve used Python 3.7 module-level `__getattr__` for a while now to allow mistyping hist.axis import as hist.axes to show a warning but work anyway. However, I completely missed a fantastic usage for Python 3.7 module-level `__dir__ `: you can “fix” IPython’s tab completion to just show the items in `__all__`! Wow! One of the main things that bugged me about importing and defining unrelated things in modules, and one reason that boost-histogram has an `_internal` module.

An example of before and after in IPython for Henry

**Before:**
Before

**After:**
After

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #1402 

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Use module level __dir__ in combination with __all__ to restrict the public API import views to useful imports
* c.f. https://snarky.ca/lazy-importing-in-python-3-7/
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
https://github.com/scikit-hep/pyhf/pull/1403/commits/287af59571f099f43365cdcaab72f270e69987d7 removes `optimize` given confusion it has caused users in Issue #1413.

**Comment by asottile** [comment]
pre-commit.ci run

**Comment by matthewfeickert** [comment]
pre-commit.ci run

**Comment by matthewfeickert** [comment]
**Before:**

```python
>>> import pyhf
>>> pyhf.
pyhf.InvalidBackend(    pyhf.Unsupported(       pyhf.default_optimizer  pyhf.infer              pyhf.optimize           pyhf.pdf                pyhf.tensor             pyhf.workspace
pyhf.InvalidOptimizer(  pyhf.Workspace(         pyhf.events             pyhf.interpolators      pyhf.optimizer          pyhf.probability        pyhf.tensorlib          
pyhf.Model(             pyhf.constraints        pyhf.exceptions         pyhf.mixins             pyhf.parameters         pyhf.set_backend(       pyhf.utils              
pyhf.PatchSet(          pyhf.default_backend    pyhf.get_backend(       pyhf.modifiers          pyhf.patchset           pyhf.simplemodels       pyhf.version 
```

**After:**

```python
>>> import pyhf
>>> pyhf.
pyhf.Model(         pyhf.Workspace(     pyhf.get_backend(   pyhf.interpolators  pyhf.optimzier      pyhf.simplemodels   pyhf.tensorlib      
pyhf.PatchSet(      pyhf.exceptions     pyhf.infer          pyhf.modifiers      pyhf.set_backend(   pyhf.tensor         pyhf.utils 
```

**Comment by matthewfeickert** [comment]
So from the top level this is the list of things that would be removed as of now:

```python
['InvalidBackend', 'InvalidOptimizer', 'Unsupported', 'constraints', 'default_backend', 'default_optimizer', 'events', 'mixins', 'optimize', 'optimizer', 'parameters', 'patchset', 'pdf', 'probability', 'version', 'workspace']
```

I think we should keep

```python
['optimizer', 'parameters', 'patchset', 'pdf', 'probability', 'workspace']
```

**Review by kratsg — APPROVED** [review]

**Comment by matthewfeickert** [comment]
Okay _now we have

**Before PR:**

```python
>>> import pyhf
>>> pyhf.
pyhf.InvalidBackend(    pyhf.Unsupported(       pyhf.default_optimizer  pyhf.infer              pyhf.optimize           pyhf.pdf                pyhf.tensor             pyhf.workspace
pyhf.InvalidOptimizer(  pyhf.Workspace(         pyhf.events             pyhf.interpolators      pyhf.optimizer          pyhf.probability        pyhf.tensorlib          
pyhf.Model(             pyhf.constraints        pyhf.exceptions         pyhf.mixins             pyhf.parameters         pyhf.set_backend(       pyhf.utils              
pyhf.PatchSet(          pyhf.default_backend    pyhf.get_backend(       pyhf.modifiers          pyhf.patchset           pyhf.simplemodels       pyhf.version 
```

**After PR:**

```python
>>> import pyhf
>>> pyhf.
pyhf.Model(         pyhf.Workspace(     pyhf.get_backend(   pyhf.interpolators  pyhf.optimizer      pyhf.patchset       pyhf.probability    pyhf.simplemodels   pyhf.tensorlib      pyhf.workspace
pyhf.PatchSet(      pyhf.exceptions     pyhf.infer          pyhf.modifiers      pyhf.parameters     pyhf.pdf            pyhf.set_backend(   pyhf.tensor         pyhf.utils  
```

**Pull request merged**
