### PR TITLE
refactor: Use multistage Docker build to include only built libraries in Docker image

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

In an attempt to decrease the size of the Docker images built even more, use a multistage Docker build to `COPY` over only the built libraries to the final Docker image without having to have Git installed or the source code in the final image.

~~add  a [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file to have the `COPY . /code` step of the `Dockerfile` ignore all files but build necessary ones.~~

~~To remove even more space if the `.git` directory is ignored and then a new `.git` repo is initialized inside the container, then the build can succeed without needing the commit history. This results in a `.git` repo with no commits, and so to avoid any future confusion from someone wondering why there is a blank `.git` repo the directory is also removed.~~

I followed the multistage build pattern shown in the blog post "[Building Minimal Docker Containers for Python Applications](https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3)".

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Use a Docker multistage build to copy over only the built Python libraries to the final image
* Use 'docker images' to show built image size at end of CI build
```

### CODE REVIEW

**Comment by lukasheinrich** [comment]
why do we need a git repo at all?

**Comment by matthewfeickert** [comment]
> why do we need a git repo at all?

In short, it is because `setuptools-scm` throws an error while trying to figure out if it is going to setup a deployment release or a dev release if it can't reference the Git history since the last release tag (c.f. PR #436).

So the following Dockerfile

```dockerfile
FROM matthewfeickert/python3-scipy-alpine:scipy-1.2.1
COPY . /code
RUN cd /code && \
    rm -rf /var/cache/apk/* && \
    python -m pip install --upgrade --no-cache-dir pip setuptools wheel && \
    python -m pip install --no-cache-dir -e .[xmlio] && \
    python -m pip list
ENTRYPOINT ["/usr/local/bin/pyhf"]
```

fails to build with the following errors

```
$ docker build . --file docker/Dockerfile --tag pyhf/pyhf:fail-example
Sending build context to Docker daemon  728.1kB
Step 1/4 : FROM matthewfeickert/python3-scipy-alpine:scipy-1.2.1
 ---> fba7df6a582c
Step 2/4 : COPY . /code
 ---> 03adab168fd8
Step 3/4 : RUN cd /code &&     rm -rf /var/cache/apk/* &&     python -m pip install --upgrade --no-cache-dir pip setuptools wheel &&     python -m pip install --no-cache-dir -e .[xmlio] &&     python -m pip list
 ---> Running in 8a866ef17779
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl (583kB)
Requirement already up-to-date: wheel in /usr/local/lib/python3.7/site-packages (0.33.6)
Installing collected packages: pip, setuptools
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed pip-19.3.1 setuptools-44.0.0
Obtaining file:///code
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpjy_9rn8v
         cwd: /code
    Complete output (36 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 111, in <module>
        use_scm_version=lambda: {'local_scheme': lambda version: ''},
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-build-env-l58bq2dm/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/code'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpjy_9rn8v Check the logs for full command output.
The command '/bin/sh -c cd /code &&     rm -rf /var/cache/apk/* &&     python -m pip install --upgrade --no-cache-dir pip setuptools wheel &&     python -m pip install --no-cache-dir -e .[xmlio] &&     python -m pip list' returned a non-zero code: 1
```

**Comment by lukasheinrich** [comment]
can't we use multistage builds do do something along the lines of `python setup.py sdist && pip install $PWD/_build`?

**Comment by matthewfeickert** [comment]
> can't we use multistage builds do do something along the lines of `python setup.py sdist && pip install $PWD/_build`?

Probably(?). I toyed around with trying to do this for about 30 minutes the other day after I opened this PR but I was having issues with getting the built Python libraries and paths properly copied over. If you have thoughts on this can you give me some more explicit/detailed hints in addition to the above? I agree that a multistage build is the preferable option to bring the size and dependencies down even more.

**Comment by lukasheinrich** [comment]
@matthewfeickert this looks great to me!

**Comment by matthewfeickert** [comment]
The `.dockerignore` file doesn't really serve any purpose anymore with the multistage build, so it can get removed.

**Comment by kratsg** [comment]
lgtm

**Pull request merged**
