### PR TITLE
docs: Add citations from Ph.D. theses on CDS

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Add citations from Ph.D. theses that are on CDS but not yet on INSPIRE:

* Add general citation from [Searching for Beyond the Standard Model Resonances in the HH→bb¯bb¯ Final State Using the ATLAS Detector](https://cds.cern.ch/record/2743178/) by @beojan.
* Add use citation from [Differential Cross Section Measurement of the pp→WH→WWW Process With the ATLAS Experiment](https://cds.cern.ch/record/2799614/) by Moritz Hesping.

(belated) Congratulations Dr. Stanislaus and Dr. Hesping! :rocket:

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add general citation from 'Searching for Beyond the Standard Model Resonances
  in the HH→bb¯bb¯ Final State Using the ATLAS Detector'.
   - c.f. https://cds.cern.ch/record/2743178/
   - Ph.D. dissertation of Beojan Stanislaus
* Add use citation from 'Differential Cross Section Measurement of the
  pp→WH→WWW Process With the ATLAS Experiment'.
   - c.f. https://cds.cern.ch/record/2799614/
   - Ph.D. dissertation of Moritz Hesping
```

### CODE REVIEW

**Comment by beojan** [comment]
The citation in my thesis is for the pyhf documentation (thanks for the really clear description of the HistFactory likelihood function by the way!) rather than the software.

The resonant version of that analysis (which is what's described in my thesis) still used HistFactory. My understanding is that the non-resonant version *does* use pyhf, but I can't say for sure since I'm not involved in that one.

**Comment by matthewfeickert** [comment]
> The citation in my thesis is for the pyhf documentation (thanks for the really clear description of the HistFactory likelihood function by the way!) rather than the software.


Thanks for the info there! Giordon had noticed the citation and mentioned it to me and I hadn't bothered to properly check myself what kind of citation when writing this up.

**Comment by matthewfeickert** [comment]
Relevant RTD build: https://pyhf--2120.org.readthedocs.build/en/2120/citations.html#use-in-publications

**Comment by matthewfeickert** [comment]
I'm going to approve and merge this myself. As always, PRs approved by a single core dev can be reverted as needed by the rest of the dev team.

**Pull request merged**
