### PR TITLE
fix: Model.spec should be self-consistent and reproducible

### LINKED ISSUE #1098: Model creation from existing model - parameter names missing in model spec?
# Question

I would like to create a new `pyhf.Model` from an existing model. This seems to work in general via `pyhf.Model(model.spec)`, see the example below. The example fails when working with a custom workspace that includes parameter specifications:

```python
import pyhf

model_hepdata = pyhf.simplemodels.hepdata_like(
    signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0]
)

# this works
pyhf.Model(model_hepdata.spec)

# custom workspace specification
ws = {
    "channels": [
        {
            "name": "SR",
            "samples": [
                {
                    "data": [
                        10.0,
                    ],
                    "modifiers": [
                        {"data": None, "name": "mu", "type": "normfactor"},
                    ],
                    "name": "Signal",
                }
            ],
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [{"bounds": [[0, 5]], "inits": [1], "name": "mu"}],
                "poi": "mu",
            },
            "name": "minimal_example",
        }
    ],
    "observations": [{"data": [12], "name": "SR"}],
    "version": "1.0.0",
}
workspace = pyhf.Workspace(ws)

# this works as well
model_from_ws = workspace.model()

# this does not work
pyhf.Model(model_from_ws.spec)
```

To make the last step work, the missing `"name"` needs to be added back into the specification:

```python
model_from_ws.spec["parameters"][0].update({"name": "mu"})
pyhf.Model(model_from_ws.spec)
```

Is this a bug?

And as another question, would this be the recommended way to create a modified model from an existing model? I would extract the `.spec`, modify that and feed it back into `pyhf.Model`.

# Relevant Issues and Pull Requests

none I'm aware of

### PR DESCRIPTION
**Pull request by kratsg**
# Pull Request Description

Resolves #1098.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR
```
* Pass in the spec directly to _ModelConfig and store a deep-copy unchanged version on Model
* Resolve bug where the spec was being modified downstream via parameter.pop()
   -  fix: change pop -> get
```

### CODE REVIEW

**Review by matthewfeickert — APPROVED** [review]
LGTM. Thanks @kratsg and thanks @alexander-held for the Issue. :shipit:

**Review by matthewfeickert — CHANGES_REQUESTED** [review]
@kratsg Actually validation tests are failing. Can you fix these?

**Comment by kratsg** [comment]
> @kratsg Actually validation tests are failing. Can you fix these?

fixed

**Review by matthewfeickert — APPROVED** [review]
:rocket:

**Pull request merged**
