### PR TITLE
docs: Add Scikit-HEP Project badge to README

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

As agreed upon in [discussion with the other members of Scikit-HEP](https://github.com/scikit-hep/scikit-hep.github.io/issues/36), Scikit-HEP projects should have a badge at the top of their README that links to the Scikit-HEP homepage. This should raise visibility of the project and help people associate different project libraries together.

[![Scikit-HEP][sk-badge]](https://scikit-hep.org/)

[sk-badge]: https://img.shields.io/badge/Scikit--HEP-Project-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAcCAYAAAB/E6/TAAAACXBIWXMAAAEZAAABGQHyCY1sAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAA6dJREFUSImdlktonFUUx/930kQ0nYo2JX5NUqSghSq2oIgvcCFaC0EEH2AXUh9FEV1UUaGIC924qY8igo+FQi26sWp8gDS24qOgCOIiKCVomLlnZpxk7Dh2GjMz389F7tgv4zfNJGdzh/M/5/zuud/ch9MKDFgnaUjSnHOu2kuOmb0h6brMMoVHgceBY8ApSVVJ05JOAnXga+BJ4OK0fO/9PZL2AL91AwwBLwLz9GYLwKvAcLtGLpcbMbM5MyuXy+UoDXI14BNFcsABYBy4DLgojDvDZH5PxJaAG4CM937SzCgUCnemQcaB0yFpDngMGFhmefuBh4E/Qt4/tVrtoJlhZq+nJWwHaiH4F2DL2QAp+SPA9wBxHDM7O5svl8vZzqBzgOkAOQGsXwmkbbVabUOj0Wh/1xIw+J+Yy+UuBJ4O4jywdTUQSSoUCgdKpRJxHC+Ees8mxVKr1WoGYf9qId77m80sNrNvgedDvb+A8yQpMzg4OJHJZPoAVavVQ6uBmNmQc+4dSfVWq7Vb0n5JC5KyknZIUiabzdYlqdFoqF6vTxSLxctXwXpNUuSce3RsbOyEc+6kpKNBG5ekjKRLguMTSUNxHE/m8/ntvRK89w9IukvS4SiK3k5Ix8N4aRu0UZIGBgaOAHdIWpfJZI56769fDlIqlTY7515yzlkcx3s65xDGjW1Qf3A0R0ZGJpxzOyX1Oee+MLMd3SDAmjiOD0paK+nB0dHRuY6QhTD2t0EWHJEkRVF0zDl3k6TTkj5OPUIkmdkzwLWSXomi6POUkNFkZxlJM8GxrR0RRdEPzrkbnXOzwHve+/s7IFc55/ZJmmq1Wvu6NH1FGGfaS3B3YrMuOTJKpdJmM5sO+2OvJBWLxUEz+9XM5vP5/DalWDhpqqHu7rYzmzhI96Ys0aZQmEKh8IKZvRV+P9GlEwEPhXoNYCgpvByE2SXCmc6GzeyncCLjvZ8EUi9N4HygEOq92SmuB/4M4pdAf2eBmZmZC7z3lQDb1AXSB3wW6vwNpF54twOtEPQBsLYzplgsfmhmpHUDnAscCvkxsCttMu3gpzhjPwNLNq2ZHU4DsXgr/5jIfa4rJJF0H0vfCp8C9wLDSRCwAdgFfBQ6gMW3wyPLQhKwK4Gv+L81m80mwKkU7Tvgmp4hHcBbgXcTf5ROqwLvA7cBblWQDmA/sLVSqXxTqVQAbmHxJXTWh0vS1vQS5JxrSJoys3JwHXHOxSuZbE+ghE1J2rJSiCT9CxJT5EBIY81lAAAAAElFTkSuQmCC

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add Scikit-HEP Project badge that links to the Scikit-HEP website
   - c.f. https://github.com/scikit-hep/scikit-hep.github.io/issues/36
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Docs are failing. Will have to check why later.

**Comment by matthewfeickert** [comment]
> Docs are failing. Will have to check why later.

Not sure why, but for whatever reason Sphinx didn't like me breaking the URL part out of the hyperlinks.

**Comment by henryiii** [comment]
Could you use the scikit-hep.org hosted version instead? See https://scikit-hep.org/developer. And could this be added to https://iris-hep.org/projects/pyhf.html too?

**Comment by matthewfeickert** [comment]
> Could you use the scikit-hep.org hosted version instead? https://scikit-hep.org/assets/images/Scikit--HEP-Project-blue.svg (see https://scikit-hep.org/developer). 

Yes! [scikit-hep.github.io PR 39](https://github.com/scikit-hep/scikit-hep.github.io/pull/39) wasn't in when I opened this, so I had just copied what was up. This is much nicer though, so thank you!

> And could this be added to https://iris-hep.org/projects/pyhf.html too?

Yes. I will open up a PR there too and then tag you Henry to merge it.

**Pull request merged**
