### PR TITLE
fix: minuit argument propagation and success check fixes

### PR DESCRIPTION
**Pull request by ntadej**
# Description

Two issues were fixed with iminuit optimizer:
 - proper argument propagation (including output level choice) - changes argument name
 - assert on valid minimum

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

### CODE REVIEW

**Comment by ntadej** [comment]
It seems that the example notebook minimisation does not really converge. How should I proceed?

**Comment by lukasheinrich** [comment]
@ntadej we can mark this as a acceptable failure for now via `pytest.mark.xfail` and proceed from there.

**Comment by ntadej** [comment]
> @ntadej we can mark this as a acceptable failure for now via `pytest.mark.xfail` and proceed from there.

Done. Not sure why codecov is not reporting though.

**Comment by lukasheinrich** [comment]
I just ran on `master` with changed default parameters

```
    def __init__(self, verbose=False, ncall=100000, errordef=1, steps=10000):
```

and with those settings the plot works

**Comment by kratsg** [comment]
With the optimizer API harmonized a lot more in #951 - I believe this got resolved. I apologize on behalf of the dev team for letting this slip by for a while, but thank you for the PR!

**Comment by matthewfeickert** [comment]
Yes, our apologies on this @ntadej. Please do let us know if you think there is anything still outstanding here as we're glad to reopen and resolve anything.

**Pull request closed without merging**
