### PR TITLE
docs: Add Altair example notebook

### PR DESCRIPTION
**Pull request by lukasheinrich**
# Description

adds an example notebook on declarative viz using altair

https://nbviewer.jupyter.org/github/scikit-hep/pyhf/blob/add_altair_example/docs/examples/notebooks/altair.ipynb?flush_cache=true

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add example notebook showcasing Altair usage and declarative nature
```

### CODE REVIEW

**Comment by lukasheinrich** [comment]
any idea why docs fail, @kratsg @matthewfeickert ?

**Comment by kratsg** [comment]
> any idea why docs fail, @kratsg @matthewfeickert ?

```
/home/runner/work/pyhf/pyhf/docs/examples.rst:11:toctree contains reference to document 'examples/notebooks/altair' that doesn't have a title: no link will be generated
```

**Comment by matthewfeickert** [comment]
I think this is really nice! It would be nice though to have a bit more text to accompany to layout for the uninitiated user what is happening.

**Comment by lukasheinrich** [comment]
done @matthewfeickert

**Comment by matthewfeickert** [comment]
@cranmer you're going to love this.

**Comment by cranmer** [comment]
Nice!!!

I tried to run on Binder with:
https://mybinder.org/v2/gh/scikit-hep/pyhf/f8c45e8?filepath=%2Fdocs%2Fexamples%2Fnotebooks%2Faltair.ipynb 

I had to `!pip install altair` in the notebook. Probably should update binder requirements. 

image

**Pull request merged**
