### PR TITLE
docs: Add general citation from Florian Bury's Ph.D. thesis

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Add general citation from [Application of deep learning techniques in CMS: from matrix element regression to the search for Higgs boson pair production](https://inspirehep.net/literature/2621189), which is @FlorianBury's Ph.D. dissertation. Congratulations Dr. Bury! :rocket:

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add general citation from 'Application of deep learning techniques in
  CMS: from matrix element regression to the search for Higgs boson pair
  production'.
   - c.f. https://inspirehep.net/literature/2621189
   - Ph.D. dissertation of Florian Bury
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Relevant RTD: https://pyhf--2092.org.readthedocs.build/en/2092/citations.html#general-citations

**Comment by FlorianBury** [comment]
Hi @matthewfeickert !
A bit unexpected for me to be honest, but I appreciate the reference, thanks !

**Comment by matthewfeickert** [comment]
docs CI is currently failing with https://github.com/sphinx-doc/sphinx/issues/11119.

**Comment by matthewfeickert** [comment]
I'm going to approve and merge this myself. As always, PRs approved by a single core dev can be reverted as needed by the rest of the dev team.

**Pull request merged**
