### PR TITLE
feat: Add ability to set default backend

### PR DESCRIPTION
**Pull request by phinate**
Adresses https://github.com/scikit-hep/pyhf/issues/1004.

Adds a `get_default_backend` function that is called instead of the global `default_backend`, meaning that one can change the default backend with `pyhf.default_backend = pyhf.tensor.tensorflow_backend(precision='64b')` or similar.

# Checklist Before Requesting Reviewer

- [ ] Tests are passing
- [ ] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

```
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@phinate Thanks for stepping up to give this a crack. :) We're all obviously happy to help out on this should you have questions.

A heads up that this is going to be a bit tricky to cleanly keep up to date as this was made from your fork's `master` branch. If we rebase this of `pyhf`'s `master` at any point GitHub will get confused and think that they will be at the same point with no version history and automatically close the PR. c.f. https://github.com/scikit-hep/pylhe/pull/27 where I learned this the hard way.

**Comment by phinate** [comment]
> @phinate Thanks for stepping up to give this a crack. :) We're all obviously happy to help out on this should you have questions.
> 
> A heads up that this is going to be a bit tricky to cleanly keep up to date as this was made from your fork's `master` branch. If we rebase this off `pyhf`'s `master` at any point GitHub will get confused and think that they will be at the same point with no version history and automatically close the PR. c.f. [scikit-hep/pylhe#27](https://github.com/scikit-hep/pylhe/pull/27) where I learned this the hard way.

Ah, this is my mistake! I was trying to port changes from a different branch to master, so my brain defaulted that of course I must keep these changes in master itself...

Is it cleaner to make a different PR from a new branch, or just to try and get tests etc passing quickly?

**Comment by matthewfeickert** [comment]
> Is it cleaner to make a different PR from a new branch, or just to try and get tests etc passing quickly?

@phinate Truly up to you. It might be easier, but I don't think it is going to break your ability to work here.

**Comment by phinate** [comment]
@matthewfeickert do you know why codefactor fails for doing `global` statements? I just copied the syntax for the normal backend, and it doesn’t flag that?

**Review by kratsg — CHANGES_REQUESTED** [review]
I have a hard time reviewing since this isn't quite so up to date with pyhf master. That said, I would like to suggest a slight improvement to the API to reduce the public namespace `pyhf` exposes:

```python
tensorlib, optimizer = pyhf.get_backend(....) # default=False by.. default.. pun intended
default_backend, default_optimizer = pyhf.get_backend(...., default=True)
pyhf.set_backend(....)
pyhf.set_backend(...., default=True)
```

This way, we can keep using the same functions that have existed for so long, continue to do the caching as normal, but simply add a shortcircuit in those functions to change the default if needed. That is, `set_backend(default=True)` will set the backend as expected, but also additionally change the default backends.

**Comment by phinate** [comment]
Not sure what went wrong with reviewing, but I'll start this again from the current `master` and a separate branch to make life easier @kratsg @matthewfeickert :)

**Pull request closed without merging**
