### PR TITLE
fix modifier table to remove per-bin subscript of Normalization

### PR DESCRIPTION
**Pull request by Moelf**
# Description

Please first read [CONTRIBUTING.md](https://github.com/scikit-hep/pyhf/tree/master/CONTRIBUTING.md).

Please describe the purpose of this pull request in some detail. Reference and link to any relevant issues or pull requests.

# Checklist Before Requesting Reviewer

- [ ] Tests are passing
- [ ] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

### CODE REVIEW

**Comment by matthewfeickert** [comment]
> Please first read [CONTRIBUTING.md](https://github.com/scikit-hep/pyhf/tree/master/CONTRIBUTING.md).

We want an Issue tied to all PRs.

**Comment by Moelf** [comment]
close #1768

**Comment by matthewfeickert** [comment]
@Moelf we can discuss this more in Issue #1768 and maybe reopen this. Bottom line is that the docs were confusing to you, which means they need to be improved in some manner. :)

**Comment by Moelf** [comment]
it's probably fine, nobody reads the subscripts and the general message is correct already

**Pull request closed without merging**
