### PR TITLE
fix: Control utils.py docstring example with .bumpversion.cfg

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Makes sure that the version number in the docstring in `src/pyhf/utils.py` is controlled through `bump2version`.

```
>>> import pyhf
>>> pyhf.utils.citation(True)
'@software{pyhf,  author = "{Heinrich, Lukas and Feickert, Matthew and Stark, Giordon}",  title = "{pyhf: v0.5.4}",  version = {0.5.4},  doi = {10.5281/zenodo.1169739},  url = {https://github.com/scikit-hep/pyhf},}'
```

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Control the docstring example version number in the src/pyhf/utils.py with .bumpversion.cfg
   - Amends PR #1210
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Related to this, as this PR adds

```toml
[bumpversion:file:src/pyhf/utils.py]
```

in the future we're going to have to figure out a way to guard

https://github.com/scikit-hep/pyhf/blob/f824afe77d9e48e90651931700ccfc3d3c268c18/src/pyhf/utils.py#L13

when we hit

```toml
[bumpversion]
current_version = 1.0.0

```

**Comment by kratsg** [comment]
> in the future we're going to have to figure out a way to guard
> 
> https://github.com/scikit-hep/pyhf/blob/f824afe77d9e48e90651931700ccfc3d3c268c18/src/pyhf/utils.py#L13


this could be done with something like

```
[bumpversion:file:src/pyhf/utils.py]
search = v{current_version}
replace = v{new_version}
```

**Comment by matthewfeickert** [comment]
> this could be done with something like
> 
> ```
> [bumpversion:file:src/pyhf/utils.py]
> search = v{current_version}
> replace = v{new_version}
> ```

But there's the `version = {0.5.4}` in the docstring example

https://github.com/scikit-hep/pyhf/blob/f824afe77d9e48e90651931700ccfc3d3c268c18/src/pyhf/utils.py#L145

how do we guard against that?

**Comment by kratsg** [comment]
> But there's the `version = {0.5.4}` in the docstring example

search = {{{current_version}}} ?

**Comment by matthewfeickert** [comment]
> `search = {{{current_version}}}` ?

No, as that hits the `{current_version}` but not `{vcurrent_version}` then, changing

```
'@software{pyhf,  author = "{Heinrich, Lukas and Feickert, Matthew and Stark, Giordon}",  title = "{pyhf: v0.5.4}",  version = {0.5.4},  doi = {10.5281/zenodo.1169739},  url = {https://github.com/scikit-hep/pyhf},}' 
```

to

```
'@software{pyhf,  author = "{Heinrich, Lukas and Feickert, Matthew and Stark, Giordon}",  title = "{pyhf: v0.5.4}",  version = {0.5.5},  doi = {10.5281/zenodo.1169739},  url = {https://github.com/scikit-hep/pyhf},}' 
```

(though safely not hitting the `SCHEMA_VERSION` if it was the same).

It might be that unless there is a way to guard it we'll have to be especially careful when we hit `v1.0.0`.

**Comment by kratsg** [comment]
```
[bumpversion:file:src/pyhf/utils.py]
search = v{current_version}
replace = v{new_version}
[bumpversion:file:src/pyhf/utils.py]
search = {{{current_version}}}
replace = {{{new_version}}}
```

does this work instead?

**Comment by matthewfeickert** [comment]
> ```
> [bumpversion:file:src/pyhf/utils.py]
> search = v{current_version}
> replace = v{new_version}
> [bumpversion:file:src/pyhf/utils.py]
> search = {{{current_version}}}
> replace = {{{new_version}}}
> ```
> 
> does this work instead?

Sadly, no as it seems we can't have multiple definitions

```
$ bump2version patch
Traceback (most recent call last):
  File "/home/feickert/.venvs/pyhf-CPU/bin/bump2version", line 8, in <module>
    sys.exit(main())
  File "/home/feickert/.venvs/pyhf-CPU/lib/python3.7/site-packages/bumpversion/cli.py", line 78, in main
    config_file, explicit_config, defaults,
  File "/home/feickert/.venvs/pyhf-CPU/lib/python3.7/site-packages/bumpversion/cli.py", line 251, in _load_configuration
    config.read_string(config_content)
  File "/usr/lib/python3.7/configparser.py", line 722, in read_string
    self.read_file(sfile, source)
  File "/usr/lib/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/usr/lib/python3.7/configparser.py", line 1065, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '<string>' [line 13]: section 'bumpversion:file:src/pyhf/utils.py' already exists
```

We might need to ask for help on `bump2version` Issues or try to find a better regex.

**Comment by matthewfeickert** [comment]
From the looks of https://github.com/c4urself/bump2version/issues/38, I don't think it is going to be possible to guard the `SCHEMA_VERSION` from `bump2version` so I think this PR should go on without trying to solve this all in one go and we might need to look for a replacement for `bump2version` that gives guard support.

**Review by kratsg — APPROVED** [review]

**Pull request merged**
